"""Golden-path engine tests: freeze the full 24-month seeded trace (T15).

These tests are the regression net for any future engine refactor (T47).
The fixtures are generated by tests/fixtures/generate_golden_traces.py and
reviewed by hand against Appendix B's trace shape (early burn, MRR ramp,
runway trough) before being frozen.
"""

import json
from pathlib import Path

import pytest
from app.engine.events import apply_event
from app.engine.loop import run_simulation
from app.engine.state import compile_blueprint

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"

EVT_001 = {
    "mechanical_impact": {
        "immediate": {
            "cac_delta_percent": 35,
            "churn_delta_percent": 15,
            "new_signups_delta_percent": -40,
            "team_morale_delta": -0.10,
            "cash_burn_delta_monthly": 0,
        }
    }
}


def _golden() -> dict:
    return json.loads((FIXTURES / "blueprint_golden.json").read_text())


def _frozen_trace(name: str) -> list[dict]:
    return json.loads((FIXTURES / name).read_text())["tick_logs"]


def test_golden_trace_matches_frozen() -> None:
    state = compile_blueprint(_golden())
    result = run_simulation(state, 24, seed=42)
    assert result.months_simulated == 24
    assert result.survived is True
    frozen = _frozen_trace("golden_trace_seed42.json")
    assert len(frozen) == 24
    for log, expected in zip(result.tick_logs, frozen, strict=True):
        assert log.month == expected["month"]
        for key, value in expected["kpis"].items():
            if key == "cash":
                assert log.kpis[key] == pytest.approx(value, abs=0.01)
            else:
                assert log.kpis[key] == value


def test_golden_trace_reproducible() -> None:
    state = compile_blueprint(_golden())
    a = run_simulation(state, 24, seed=42)
    b = run_simulation(state, 24, seed=42)
    assert [t.kpis for t in a.tick_logs] == [t.kpis for t in b.tick_logs]


def test_golden_event_trace_matches_frozen() -> None:
    """Inject evt_001 at the start of month 7; months align 1:1 with baseline."""
    state = compile_blueprint(_golden())
    frozen = _frozen_trace("golden_trace_seed42_evt001.json")
    import random

    from app.engine.loop import _customer_movement, _kpi_snapshot, tick

    sim = state.snapshot()
    rng = random.Random(42)
    prev = sim
    logs = []
    for m in range(1, 25):
        if m == 7:
            sim = apply_event(sim, EVT_001["mechanical_impact"], month=7)
        prev = sim
        sim = tick(sim, rng)
        new_customers, churned_customers = _customer_movement(prev, sim)
        logs.append(
            {"month": m, "kpis": _kpi_snapshot(sim, new_customers, churned_customers)}
        )
        if sim.bankrupt:
            break

    assert len(logs) == len(frozen)
    for log, expected in zip(logs, frozen, strict=True):
        assert log["month"] == expected["month"]
        for key, value in expected["kpis"].items():
            if key == "cash":
                assert log["kpis"][key] == pytest.approx(value, abs=0.01)
            else:
                assert log["kpis"][key] == value


def test_golden_event_reduces_month7_customers() -> None:
    """The evt_001 stress run has strictly fewer customers at month 7 than baseline."""
    baseline = _frozen_trace("golden_trace_seed42.json")
    evt = _frozen_trace("golden_trace_seed42_evt001.json")
    baseline_m7 = next(t["kpis"]["customers"] for t in baseline if t["month"] == 7)
    evt_m7 = next(t["kpis"]["customers"] for t in evt if t["month"] == 7)
    assert evt_m7 < baseline_m7
