"""
Celery task: walk a report manifest section-by-section,
publish progress to Redis, and log each step.
Sections are generated by the LLM section writer and linted with a
deterministic retry-then-fallback flow (Day 03); the assembled PDF is
written on completion (Day 05).
"""
from __future__ import annotations

import asyncio
import json
import threading
from collections.abc import Callable
from contextlib import suppress
from pathlib import Path
from typing import Any

import structlog
from redis.asyncio import Redis

from app.agents.section_writer import generate_section, render_data_only_fallback
from app.core.config import get_settings
from app.core.exceptions import StructuredOutputError
from app.services.deep_report.data_pack import build_data_pack
from app.services.deep_report.manifest import ReportTier
from app.services.deep_report.registry import get_manifest
from app.services.deep_report.section_linter import lint_section
from app.workers.celery_app import celery_app

logger = structlog.get_logger("forge.report_job")

REDIS_PROGRESS_KEY = "deep_report:progress:{job_id}"
REDIS_CHANNEL = "deep_report:{job_id}"


async def _publish_progress(
    redis: Redis | None,
    job_id: str,
    run_id: str,
    tier: str,
    section: int,
    total: int,
    status: str,
    title: str,
) -> None:
    """Publish section progress to Redis for WebSocket forwarding (best-effort)."""
    if redis is None:
        return
    payload = json.dumps(
        {
            "job_id": job_id,
            "run_id": run_id,
            "tier": tier,
            "section": section,
            "total": total,
            "status": status,  # "writing" | "linting" | "done" | "error"
            "section_title": title,
        }
    )
    with suppress(Exception):
        await redis.publish(REDIS_CHANNEL.format(job_id=job_id), payload)
        await redis.set(REDIS_PROGRESS_KEY.format(job_id=job_id), payload, ex=3600)


def _task(name: str) -> Callable[[Callable[..., Any]], Any]:
    # Celery's untyped decorator returns Any; cast keeps mypy quiet.
    return celery_app.task(name=name)  # type: ignore[no-any-return]


def _run_coro(coro: Any) -> Any:
    """Run a coroutine from a sync Celery task and return its result.

    In a real worker there is no running loop, so ``asyncio.run`` is correct.
    Under pytest's eager mode the task runs inside the test's event loop,
    where ``asyncio.run`` raises — execute the coroutine on a dedicated
    thread with its own loop and block until it finishes.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)

    result: dict[str, Any] = {}

    def _target() -> None:
        result["value"] = asyncio.run(coro)

    thread = threading.Thread(target=_target, daemon=True)
    thread.start()
    thread.join()
    return result.get("value")


@_task("forge.generate_deep_report")
def generate_deep_report(
    job_id: str, run_id: str, report_type: str, tier: str
) -> dict[str, Any]:
    """
    Walk the manifest for the given report_type and tier.
    For each section:
      1. Build the deterministic data pack
      2. Call the section writer (DeepSeek via bridge)
      3. Run the section linter; retry once, then fall back to data-only
      4. [Day 05] Assemble into PDF
    """

    async def _run() -> dict[str, Any]:
        settings = get_settings()
        redis: Redis | None = None
        try:
            redis = Redis.from_url(settings.redis_url, decode_responses=True)
        except Exception:  # noqa: BLE001 - best-effort
            redis = None

        manifest = get_manifest(report_type)
        tier_enum = ReportTier(tier)
        sections = manifest.sections_for_tier(tier_enum)
        total = len(sections)

        logger.info(
            "deep report: starting",
            job_id=job_id,
            run_id=run_id,
            report_type=report_type,
            tier=tier,
            sections=total,
        )

        from app.db.session import async_session_factory

        results: list[dict[str, Any]] = []

        for idx, section in enumerate(sections, start=1):
            await _publish_progress(
                redis, job_id, run_id, tier, idx, total, "writing", section.title
            )
            logger.info(
                "deep report: writing section",
                job_id=job_id,
                section=f"{idx}/{total}",
                title=section.title,
            )

            # Data pack (deterministic engine/stored data; never fabricated)
            async with async_session_factory() as db:
                data_pack = await build_data_pack(section, run_id, db)

            if not section.ai_generated:
                section_output = render_data_only_fallback(section, data_pack)
            else:
                try:
                    section_output = await generate_section(section, data_pack)
                    await _publish_progress(
                        redis, job_id, run_id, tier, idx, total, "linting", section.title
                    )
                    lint = lint_section(section, section_output, data_pack)
                    if not lint.passed:
                        logger.warning(
                            "deep report: lint failed, retrying",
                            job_id=job_id,
                            section=idx,
                            errors=lint.errors,
                        )
                        section_output = await generate_section(section, data_pack)
                        lint2 = lint_section(section, section_output, data_pack)
                        if not lint2.passed:
                            logger.error(
                                "deep report: lint failed twice, using fallback",
                                job_id=job_id,
                                section=idx,
                                errors=lint2.errors,
                            )
                            section_output = render_data_only_fallback(section, data_pack)
                except StructuredOutputError as exc:
                    logger.error(
                        "deep report: structured output failed, using fallback",
                        job_id=job_id,
                        section=idx,
                        error=str(exc),
                    )
                    section_output = render_data_only_fallback(section, data_pack)

            results.append(section_output)

            await _publish_progress(
                redis, job_id, run_id, tier, idx, total, "done", section.title
            )

        logger.info("deep report: completed", job_id=job_id, total_sections=len(results))

        # Assemble and save the PDF (best-effort — section results are already
        # collected; a PDF failure is surfaced in the returned payload).
        pdf_path: str | None = None
        try:
            settings = get_settings()
            from app.services.deep_report.assembler import assemble_report
            from app.services.deep_report.data_pack import (
                _extract_mc_aggregates,
                _fetch_run,
                _fetch_tick_logs,
            )

            async with async_session_factory() as db:
                run = await _fetch_run(run_id, db)
                ticks = await _fetch_tick_logs(run_id, db)
                mc = _extract_mc_aggregates(run) or {}
                workspace_name = "Workspace"
                if run is not None:
                    from app.models.workspace import Workspace

                    ws = await db.get(Workspace, run.workspace_id)
                    workspace_name = ws.name if ws is not None else "Workspace"

            storage_dir = Path(settings.report_storage_dir)
            storage_dir.mkdir(parents=True, exist_ok=True)
            output_path = str(storage_dir / f"{job_id}.pdf")

            final_path = await assemble_report(
                results,
                ticks,
                mc,
                run_id,
                workspace_name,
                tier,
                output_path=output_path,
            )
            pdf_path = final_path
            logger.info("deep report: pdf saved", job_id=job_id, path=final_path)
        except Exception:  # noqa: BLE001 - PDF assembly must not fail the job
            logger.error("deep report: pdf assembly failed", job_id=job_id, exc_info=True)

        if redis is not None:
            with suppress(Exception):
                await redis.close()

        return {
            "job_id": job_id,
            "run_id": run_id,
            "sections_completed": len(results),
            "status": "complete",
            "pdf_path": pdf_path,
        }

    return _run_coro(_run())  # type: ignore[no-any-return]
