"""
Celery task: walk a report manifest section-by-section,
publish progress to Redis, and log each step.
DeepSeek section generation is stubbed — added Day 03.
"""
from __future__ import annotations

import asyncio
import json
import threading
from collections.abc import Callable
from contextlib import suppress
from typing import Any

import structlog
from redis.asyncio import Redis

from app.core.config import get_settings
from app.services.deep_report.data_pack import build_data_pack
from app.services.deep_report.manifest import ReportTier
from app.services.deep_report.registry import get_manifest
from app.workers.celery_app import celery_app

logger = structlog.get_logger("forge.report_job")

REDIS_PROGRESS_KEY = "deep_report:progress:{job_id}"
REDIS_CHANNEL = "deep_report:{job_id}"


async def _publish_progress(
    redis: Redis | None,
    job_id: str,
    section: int,
    total: int,
    status: str,
    title: str,
) -> None:
    """Publish section progress to Redis for WebSocket forwarding (best-effort)."""
    if redis is None:
        return
    payload = json.dumps(
        {
            "job_id": job_id,
            "section": section,
            "total": total,
            "status": status,  # "writing" | "linting" | "done" | "error"
            "section_title": title,
        }
    )
    with suppress(Exception):
        await redis.publish(REDIS_CHANNEL.format(job_id=job_id), payload)
        await redis.set(REDIS_PROGRESS_KEY.format(job_id=job_id), payload, ex=3600)


def _task(name: str) -> Callable[[Callable[..., Any]], Any]:
    # Celery's untyped decorator returns Any; cast keeps mypy quiet.
    return celery_app.task(name=name)  # type: ignore[no-any-return]


def _run_coro(coro: Any) -> Any:
    """Run a coroutine from a sync Celery task and return its result.

    In a real worker there is no running loop, so ``asyncio.run`` is correct.
    Under pytest's eager mode the task runs inside the test's event loop,
    where ``asyncio.run`` raises — execute the coroutine on a dedicated
    thread with its own loop and block until it finishes.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)

    result: dict[str, Any] = {}

    def _target() -> None:
        result["value"] = asyncio.run(coro)

    thread = threading.Thread(target=_target, daemon=True)
    thread.start()
    thread.join()
    return result.get("value")


@_task("forge.generate_deep_report")
def generate_deep_report(
    job_id: str, run_id: str, report_type: str, tier: str
) -> dict[str, Any]:
    """
    Walk the manifest for the given report_type and tier.
    For each section:
      1. Build the deterministic data pack
      2. [Day 03] Call section writer (DeepSeek)
      3. [Day 03] Run section linter
      4. [Day 05] Assemble into PDF
    Today: logs + publishes progress only.
    """

    async def _run() -> dict[str, Any]:
        settings = get_settings()
        redis: Redis | None = None
        try:
            redis = Redis.from_url(settings.redis_url, decode_responses=True)
        except Exception:  # noqa: BLE001 - best-effort
            redis = None

        manifest = get_manifest(report_type)
        tier_enum = ReportTier(tier)
        sections = manifest.sections_for_tier(tier_enum)
        total = len(sections)

        logger.info(
            "deep report: starting",
            job_id=job_id,
            run_id=run_id,
            report_type=report_type,
            tier=tier,
            sections=total,
        )

        from app.db.session import async_session_factory

        results: list[dict[str, Any]] = []

        for idx, section in enumerate(sections, start=1):
            await _publish_progress(redis, job_id, idx, total, "writing", section.title)
            logger.info(
                "deep report: writing section",
                job_id=job_id,
                section=f"{idx}/{total}",
                title=section.title,
            )

            # Data pack (stub returns empty keys today; fleshed out Day 02)
            async with async_session_factory() as db:
                data_pack = await build_data_pack(section, run_id, db)

            # Placeholder: section content will be generated Day 03
            section_result = {
                "section_number": section.section_number,
                "title": section.title,
                "status": "stub",
                "content": (
                    f"# {section.title}\n\n"
                    "_Content will be generated by DeepSeek (Day 03)._"
                ),
                "data_pack_keys": list(data_pack.keys()),
            }
            results.append(section_result)

            await _publish_progress(redis, job_id, idx, total, "done", section.title)

        logger.info("deep report: completed", job_id=job_id, total_sections=len(results))

        if redis is not None:
            with suppress(Exception):
                await redis.close()

        return {
            "job_id": job_id,
            "run_id": run_id,
            "sections_completed": len(results),
            "status": "stub_complete",
        }

    return _run_coro(_run())  # type: ignore[no-any-return]
