"""add blueprints and blueprint_versions

Revision ID: a1b2c3d4e5f6
Revises: edef23679073
Create Date: 2026-08-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'edef23679073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _jsonb() -> sa.types.TypeEngine:
    """JSONB on Postgres, plain JSON on sqlite (tests/dev)."""
    return postgresql.JSONB(astext_type=sa.Text()).with_variant(
        sqlite.JSON(), "sqlite"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_workspace_id'), 'blueprints', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_blueprints_workspace_updated'), 'blueprints', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('blueprint_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('blueprint_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', _jsonb(), nullable=False),
    sa.Column('vulnerabilities', _jsonb(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'version')
    )
    op.create_index(op.f('ix_blueprint_versions_blueprint_id'), 'blueprint_versions', ['blueprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprint_versions_blueprint_id'), table_name='blueprint_versions')
    op.drop_table('blueprint_versions')
    op.drop_index(op.f('ix_blueprints_workspace_updated'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_workspace_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
