"""leaderboard + share columns

Revision ID: c3d4e5f6a7b9
Revises: b2c3d4e5f6a8
Create Date: 2026-08-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b9'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'simulation_runs',
        sa.Column('is_public', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column('reports', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(
        op.f('ix_reports_share_token'), 'reports', ['share_token'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_share_token'), table_name='reports')
    op.drop_column('reports', 'share_token')
    op.drop_column('simulation_runs', 'is_public')
    # ### end Alembic commands ###
