"""add simulation runs, tick logs, events, decisions

Revision ID: c7d2e8f1a3b4
Revises: a1b2c3d4e5f6
Create Date: 2026-08-05 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision: str = 'c7d2e8f1a3b4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _jsonb() -> sa.types.TypeEngine:
    """JSONB on Postgres, plain JSON on sqlite (tests/dev)."""
    return postgresql.JSONB(astext_type=sa.Text()).with_variant(
        sqlite.JSON(), "sqlite"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_version_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('current_month', sa.Integer(), nullable=False),
    sa.Column('config', _jsonb(), nullable=False),
    sa.Column('result', _jsonb(), nullable=True),
    sa.Column('state_snapshot', _jsonb(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_bpv_id'), 'simulation_runs', ['blueprint_version_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_workspace_created'), 'simulation_runs', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_simulation_runs_workspace_id'), 'simulation_runs', ['workspace_id'], unique=False)
    op.create_table('tick_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('kpis', _jsonb(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'month')
    )
    op.create_index(op.f('ix_tick_logs_run_id'), 'tick_logs', ['run_id'], unique=False)
    op.create_table('simulation_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('payload', _jsonb(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_events_run_id'), 'simulation_events', ['run_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('option_id', sa.String(length=16), nullable=False),
    sa.Column('projection', _jsonb(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['simulation_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_simulation_events_run_id'), table_name='simulation_events')
    op.drop_table('simulation_events')
    op.drop_index(op.f('ix_tick_logs_run_id'), table_name='tick_logs')
    op.drop_table('tick_logs')
    op.drop_index(op.f('ix_simulation_runs_workspace_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_workspace_created'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_bpv_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
