"""add actuals_records table

Revision ID: e5f159bb8292
Revises: e6f7a8b9c0d1
Create Date: 2026-08-20 08:42:36.063786

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision: str = 'e5f159bb8292'
down_revision: str | Sequence[str] | None = 'e6f7a8b9c0d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _jsonb() -> sa.types.TypeEngine:
    """JSONB on Postgres, plain JSON on sqlite (tests/dev)."""
    return postgresql.JSONB(astext_type=sa.Text()).with_variant(
        sqlite.JSON(), "sqlite"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuals_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('blueprint_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('fields', _jsonb(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actuals_blueprint_id', 'actuals_records', ['blueprint_id'], unique=False)
    op.create_index('ix_actuals_workspace_id', 'actuals_records', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actuals_workspace_id', table_name='actuals_records')
    op.drop_index('ix_actuals_blueprint_id', table_name='actuals_records')
    op.drop_table('actuals_records')
    # ### end Alembic commands ###
