"""create reports table

Revision ID: e5f6a7b8c9d0
Revises: c7d2e8f1a3b4
Create Date: 2026-08-05 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision: str = 'e5f6a7b8c9d0'
down_revision: Union[str, Sequence[str], None] = 'c7d2e8f1a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _jsonb() -> sa.types.TypeEngine:
    """JSONB on Postgres, plain JSON on sqlite (tests/dev)."""
    return postgresql.JSONB(astext_type=sa.Text()).with_variant(
        sqlite.JSON(), "sqlite"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('content_json', _jsonb(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_run_id'), 'reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_reports_run_type'), 'reports', ['run_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_run_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_run_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
