"""add onboarding fields to users

Revision ID: f7a8b9c0d1e2
Revises: e5f6a7b8c9d0
Create Date: 2026-08-06 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f7a8b9c0d1e2'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('industry', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('stage', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('primary_fear', sa.String(length=500), nullable=True))
    op.add_column(
        'users',
        sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'primary_fear')
    op.drop_column('users', 'stage')
    op.drop_column('users', 'industry')
    # ### end Alembic commands ###
