from __future__ import annotations

import csv
import io
import json
import os
import zipfile
from datetime import UTC, datetime, timedelta
from typing import Any

from itsdangerous import URLSafeTimedSerializer
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_redis
from app.core.config import get_settings

REDIS_PREFIX = "dataroom:"


def _get_serializer() -> URLSafeTimedSerializer:
    settings = get_settings()
    return URLSafeTimedSerializer(settings.jwt_secret_key, salt="dataroom")


def _storage_dir() -> str:
    settings = get_settings()
    return settings.report_storage_dir


async def create_dataroom(
    run_id: str,
    label: str,
    expiry_days: int,
    pdf_path: str | None,
    tick_logs: list[dict[str, Any]],
    mc_aggregates: dict[str, Any],
    workspace_name: str,
    db: AsyncSession,
) -> dict[str, Any]:
    """Bundle PDF + CSV exports and create a signed expiring data room link."""
    s = _get_serializer()
    token = s.dumps({"run_id": run_id, "workspace": workspace_name})
    short_token = token[:16]
    expires_at = datetime.now(UTC) + timedelta(days=expiry_days)

    # Build ZIP bundle.
    storage_dir = _storage_dir()
    bundle_path = os.path.join(storage_dir, f"dataroom_{short_token}.zip")
    os.makedirs(storage_dir, exist_ok=True)

    with zipfile.ZipFile(bundle_path, "w") as zf:
        # Include PDF if available.
        if pdf_path and os.path.exists(pdf_path):
            zf.write(pdf_path, "simulation_audit.pdf")

        # KPI CSV export.
        if tick_logs:
            buf = io.StringIO()
            writer = csv.DictWriter(buf, fieldnames=list(tick_logs[0].keys()))
            writer.writeheader()
            writer.writerows(tick_logs)
            zf.writestr("kpi_ticks.csv", buf.getvalue())

        # MC aggregates JSON.
        zf.writestr("mc_aggregates.json", json.dumps(mc_aggregates, indent=2))

        # Methodology note.
        zf.writestr(
            "methodology.txt",
            "Generated by The Forge Business Simulation Engine.\n"
            "All financial projections are deterministic simulations, not guarantees.",
        )

    # Store metadata in Redis.
    meta = {
        "run_id": run_id,
        "label": label,
        "token": token,
        "created_at": datetime.now(UTC).isoformat(),
        "expires_at": expires_at.isoformat(),
        "view_count": 0,
        "bundle_path": bundle_path,
    }
    redis = get_redis()
    ttl = int((timedelta(days=expiry_days + 1)).total_seconds())
    await redis.setex(f"{REDIS_PREFIX}{short_token}", ttl, json.dumps(meta))

    return {
        "token": short_token,
        "download_url": f"/api/v1/dataroom/{short_token}/download",
        "expires_at": expires_at.isoformat(),
        "label": label,
    }


async def get_dataroom(short_token: str) -> dict[str, Any] | None:
    redis = get_redis()
    raw = await redis.get(f"{REDIS_PREFIX}{short_token}")
    if not raw:
        return None
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        return None
    meta: dict[str, Any] = parsed
    # Check expiry.
    expires_at = datetime.fromisoformat(meta["expires_at"])
    if datetime.now(UTC) > expires_at:
        return None
    return meta


async def record_view(short_token: str) -> None:
    redis = get_redis()
    raw = await redis.get(f"{REDIS_PREFIX}{short_token}")
    if not raw:
        return
    meta = json.loads(raw)
    meta["view_count"] = int(meta.get("view_count", 0)) + 1
    ttl = await redis.ttl(f"{REDIS_PREFIX}{short_token}")
    await redis.setex(f"{REDIS_PREFIX}{short_token}", max(ttl, 1), json.dumps(meta))


async def revoke_dataroom(short_token: str) -> None:
    redis = get_redis()
    await redis.delete(f"{REDIS_PREFIX}{short_token}")
